### ISSUE TITLE
Can't run ski in system mode

### ISSUE THREAD

**Issue by DragonSWDev** [trofi/ski#6]
I built GCC (14.2) for ia64-unknown-linux target and Linux 4.19 using that GCC build but when I tried to run ski in system mode it didn't work for some reason. I'm trying to run system image containing Gentoo stage3 IA-64 installation. bski shuts down as soon as it starts up without any message in the console. In ski when I tried to use "run" command I've got this error:

> unable to create console window

Am I missing something?

**Comment by trofi** [comment]
Do you have `xterm` in the `PATH` by chance? It's needed to create a console to print the output. The error handling is not great when `xterm` is missing.

**Comment by DragonSWDev** [comment]
I didn't have it installed at all. After I installed it emulator started to work and I was able to boot Gentoo installation. Adding a note about it to the README probably wouldn't be a bad idea. Is there any option to use another terminal for bski? Using xterm on HiDPI screen is not very good experience.

**Comment by trofi** [comment]
Expanding the `README` sounds reasonable. I'll also try to improve error reporting to make it less obscure.

No other option than `xterm` today unfortunately :(

At least in theory anything that is able to behave like a pseudo terminal should do (like `screen` in any terminal): https://github.com/trofi/ski/blob/master/src/fake-xterm/ski-fake-xterm.c. But it will need a bit more plumbing than we have today.

**Comment by DragonSWDev** [comment]
I get it. It works now so I think I can close it. Thank you for your help and your work.

**Comment by johnny-mnemonic** [comment]
@trofi, @DragonSWDev: Let me add a few things. I used ski to some extent by now, also did some light "benchmarking" in the first half of December. In addition to using xterm, there's also the possiblity to use ski with the current shell. The option - `-noconsole` - to do that is a little misnamed I think but it works. I didn't find a way to stop the simulation from inside ski that way, so one needs to for example send a SIGINT to it from another shell to stop the simulation, but that sometimes also tears up the shell where ski is running in (e.g. no visible reaction to input, but one can blindly invoke `reset`, but cumbersome). To avoid that, I run it with `screen`, e.g. like so:

```
# screen /opt/ski/bin/bski -noconsole \
./ski-bootloader-test3 \
/boot/vmlinux-6.13.0-rc1-21127f604-ia64-ski-tmpfs-64k-g21127f604a03 \
root=/dev/sda simscsi=./sd simeth=eth4000000013 init=/init PATH=/bin:/sbin:/usr/bin:/usr/sbin rw
```

This way I can just end the simulation by ending `screen` (i.e. ctrl + a + k). I'm interested in remote-controlling the simulated machine from the host and so far I was able to do that via network. Which seems to require a separate interface - I didn't find another way so far. I use a USB to Ethernet adapter with shortened name, because the interface name has to be less than 14 characters. That way I was able to connect via telnet from the host to the simulation. But that has a high latency upon connection and login, so I later went for a bind shell that has much lower latency and also doesn't require a login. I created a tool named `ia64-run` that executes ia64 binaries inside ski via that bind shell and forwards the exit code to the host:

```
root@esprimo-e420:~# time ia64-run arch
ia64

real	0m0.459s
user	0m0.009s
sys	0m0.001s

root@esprimo-e420:~# ia64-run false
root@esprimo-e420:~# echo $?
1
root@esprimo-e420:~# ia64-run true
root@esprimo-e420:~# echo $?
0

root@esprimo-e420:~# ia64-run 'cat /proc/cpuinfo'
processor  : 0
vendor     : HP Ski Simulator
arch       : IA-64
family     : 31
model      : 0
model name : McKinley
revision   : 0
archrev    : 0
features   : branchlong, 16-byte atomic ops
cpu number : 0
cpu regs   : 4
cpu MHz    : 40.000
itc MHz    : 40.000000
BogoMIPS   : 26.50
siblings   : 1
```

It can also be used to get the host timing for instrumented shell code, by scanning the output of the command running in ski for specific keywords and reacting on the host with - in this case - to get the seconds since epoch. This way I can determine how long parts of a package build (for e.g. [EPIC Slack](http://epic-slack.org/)) take inside ski and compare that to how they perform on a real machine:

```
root@esprimo-e420:~ time ia64-run \
'cd /srv/slackware; . ./env; cd slackware64-current/source; /root/bin/es-build.bash n/iftop' \
2>n-iftop-build.timing
```

It needs a network connection though. It would be nice to have that kind of remote control also w/o network, though not there yet. But for what I have in mind for the future, i.e. executing cross-compiled test binaries for gcc or glibc or whatever inside ski it'd need a network connection anyhow for data exchange via NFS for example (which works fine BTW).

**Comment by trofi** [comment]
Yeah, I don't think there is a special interface for anything like that. I wonder if `qemu` has anything standard to implement there. `ia64`'s naatural way would probably to expose it via some PAL/SAL calls.

Generally all the interaction between the guest and host is based on the guest initiating requests to host via hypercall-like requests: https://github.com/trofi/ski/blob/master/ski-bootloader/ssc.h#L12

For example ski boot loader uses it via `ssc()` to get/put bytes on the tty or read an actual kernel from host into the guest memory. Guest kernel also uses `ssc()` equivalent to fetch things from host `ski`, for thing like current time https://github.com/trofi/ski/blob/ca50b9326087556e82810fa2f01cd3394daad95c/src/linux/syscall-linux.c#L4778 (host's side) or even read or write arbitrary files from the guest (VERY UNSAFE).

On caller's guest side `ssc()` is implemented as a `break` style syscall: https://github.com/trofi/ski/blob/ca50b9326087556e82810fa2f01cd3394daad95c/ski-bootloader/boot_head.S#L39 :  `break 0x80001`. I wonder if it is allowed to get that called from guest's userspace (I suspect we will corrupt giest's kernel memory by confusing pointers with guest's userspace, but maybe not?). If it works as is you might be able to run a guest agent that does these hypercalls and tell the host agent to do something fancy (say, most general complex solution would be to a FIFO or UNIX socket on host via SSC and have a trivial bi-directional RPC interface).

And if you are willing to patch `ski` a bit you can add more hypercalls to talk to the `ski` directory from the guest to cover your needs.
